apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    groups: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key:app, operation: In, values: [second-app, first-app]}
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: nurfaisal/kube-first-app:2
      #  - name:
      #    image:        